
spring:
  datasource:
    url: 'jdbc:h2:mem:SNOCDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS SNOC_NOMINATION'
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: true
    show-sql: false
  h2:
    console:
      enabled: true
hibernate:
  show_sql: false
