name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          gradle-version: '7.4.3'  # Specify the version of Gradle you want to use
          arguments: build
          working-directory: nomination-be
      - name: Build the Docker image
        run: docker build nomination-be/customer-manager --file nomination-be/customer-manager/Dockerfile --tag customer-manager:$(date +%s)
